### ISSUE TITLE
UnboundLocalError: local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by jmrichardson** [uqfoundation/klepto#86] opened 2020-08-31 01:53 UTC
Hi  @mmckerns , 

I am testing the code you gave in issue #81 with cached=False instead of True.  I have also made sure that the file "foo.h5" doesn't exist before running the foo function:

```
import klepto as kl
c = kl.inf_cache(cache=kl.archives.hdf_archive('foo.h5', cached=False))
@c
def foo(x):
  print('called')
  return x*x*x

foo(4)
```

This is the error:

```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_archives.py", line 2168, in __getitem__
    val = self._loadval(self._attrs(f)[self._dumpkey(key)])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'L5811844914677825734L\n.' doesn't exist)"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_cache.py", line 310, in wrapper
    result = cache[key]
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_archives.py", line 2171, in __getitem__
    raise KeyError(key)
KeyError: 5811844914677825734
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_archives.py", line 2168, in __getitem__
    val = self._loadval(self._attrs(f)[self._dumpkey(key)])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'L5811844914677825734L\n.' doesn't exist)"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_cache.py", line 317, in wrapper
    result = cache[key]
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_archives.py", line 2171, in __getitem__
    raise KeyError(key)
KeyError: 5811844914677825734
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\h5py\_hl\files.py", line 185, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file is already open for read-only)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_archives.py", line 2183, in __setitem__
    f = hdf.File(filename, 'a')
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\h5py\_hl\files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (file exists)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b0fe1665ed37>", line 8, in <module>
    foo(4)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_cache.py", line 322, in wrapper
    cache[key] = result
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\klepto\_archives.py", line 2194, in __setitem__
    if f is not None: f.close()
UnboundLocalError: local variable 'f' referenced before assignment
```

**Comment by mmckerns** [comment] 2020-08-31 12:12
@jmrichardson:  I can confirm this bug.  On quick inspection, `f` should be defined in either case of the `try`/`except` block -- so, it will need a little more investigation.  Thanks for reporting.

**Comment by mmckerns** [comment] 2020-08-31 13:28
Looks like the originating issue is: `KeyError: "Unable to open object (object 'L5811844914677825734L\n.' doesn't exist)"`.  I just checked python 2.7, and it works... so I assume that the issue probably derives from a python 2 to 3 string issue in the code.

**Comment by mmckerns** [comment] 2020-08-31 13:48
Definitely a byte/string error from python 3.
```
>>> import klepto as kl
>>> c = kl.inf_cache(cache=kl.archives.hdf_archive('foo.h5', cached=False))
>>> @c
... def foo(x):
...   print('called')
...   return x*x*x
... 
>>> ar = foo.__cache__()
>>> ar[b'yyy'] = 4
>>> ar[b'yyy']    
4
>>> ar['xxx'] = 4
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 185, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file is already open for read-only)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.6/site-packages/klepto/_archives.py", line 2183, in __setitem__
    f = hdf.File(filename, 'a')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (file exists)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.6/site-packages/klepto/_archives.py", line 2194, in __setitem__
    if f is not None: f.close()
UnboundLocalError: local variable 'f' referenced before assignment
```

**Comment by mmckerns** [comment] 2020-09-05 18:13
Looks like this is the root cause: `OSError: Unable to open file (file is already open for read-only)` -- somewhere the archive is opened, but not closed properly. HDF5 will not write to an already opened file from a second file handle.

**Comment by jmrichardson** [comment] 2020-09-05 19:55
Thank you and will try to see what has it open.  Appreciate the help!

**Comment by mmckerns** [comment] 2020-09-05 22:25
I believe this is actually a bug, and needs to be fixed.

**Comment by mmckerns** [comment] 2020-09-05 22:30
```
>>> ar['x']
...
KeyError: 'x'
>>> ar['x'] = 5
...
UnboundLocalError: local variable 'f' referenced before assignment
>>> ar['x'] = 5
>>>
```
I can reproduce the error when attempting to setitem that just elicited a KeyError upon a getitem.   So, it's one of the file handlers that is not closing in python 3 (or maybe due to a newer version of `h5py`.  I do see that `h5py` is changing the way that it handles opening and writing to files.

**Closed** 2020-09-05 23:18 UTC
Labels: bug

**Comment by mmckerns** [comment] 2020-09-05 23:19
Reopen if this doesn't fix it for you.
